services:
  python:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}

    container_name: python-esgi
    volumes:
      - ./src:/workspace

    # A changer selon les besoins de votre projet
    ports:
      - "8000:8000"
    working_dir: /workspace
    command: tail -f /dev/null
    tty: true